name: Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: build and push
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        username: "hydrocode-de"
        password: ${{ secrets.PAT }}
        repository: camels-de/camels-serv
        tags: latest,${{ github.ref_name }}

    - name: Run new image
      uses: garygrossgarten/github-action-ssh@latest
      with:
      command: | 
        docker container stop camels_serv
        docker container rm camels_serv
        docker run -d -p 8042:5000 --restart always --name camels_serv  -v /home/camels:/src/dev ghcr.io/camels-de/camels-serv:${{ github.ref_name }}
      host: ${{ secrets.HOST }}
      passphrase: ${{ secrets.PASSPHRASE }}
      username: ${{ secrets.USER }}
